alias: Check Light Mood
description: If lights not on default (Dark, Relaxed or Bright) set to Unknown
trigger:
    platform: time_pattern
    # You can also match on interval. This will match every 5 minutes
    minutes: "/5"
condition:
  - condition: state
    entity_id: light.living_room
    state: 'on'
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.harmony_state
      option: > 
        {% if states.light.living_room.color_temp == 454 
          and states.light.living_room.brightness == 1
        %}
            Dark
        {% elif if states.light.living_room.color_temp == 400 
          and states.light.living_room.brightness == 170
        %}
            Relaxed
        {% elif if states.light.living_room.color_temp == 250 
          and states.light.living_room.brightness == 254
        %}
            Bright
        {% else %}
            Unknown
        {% endif %}