- action:
  - data:
      brightness: 254
      entity_id: light.livingroom_light
    service: light.turn_on
  alias: Set Bright
  condition: []
  id: '1523967039617'
  trigger:
  - entity_id: input_select.light_state
    platform: state
    to: Bright
- action:
  - data:
      brightness: 60
      entity_id: light.livingroom_light
    service: light.turn_on
  alias: Set Dark
  condition: []
  id: '1523967151515'
  trigger:
  - entity_id: input_select.light_state
    platform: state
    to: Dark
- action:
  - data:
      brightness: 160
      entity_id: light.livingroom_light
    service: light.turn_on
  alias: Set Relaxed
  condition: []
  id: '1523967215462'
  trigger:
  - entity_id: input_select.light_state
    platform: state
    to: Relaxed
- action:
  - data:
      entity_id: light.livingroom_light
    service: light.turn_off
  - data:
      entity_id: input_select.light_state
      option: 'Off'
    service: input_select.select_option
  alias: Set Off
  condition: []
  id: '1523967332497'
  trigger:
  - entity_id: input_select.light_state
    platform: state
    to: 'Off'
  - entity_id: light.livingroom_light
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: switch.wall_switch_158d0001a68d54
    service: switch.turn_off
  alias: Turn off Utility Light if kitchen light off
  condition: []
  id: '1524078182191'
  trigger:
  - entity_id: switch.wall_switch_158d000159a94f
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: input_select.light_state
      option: Bright
    service: input_select.select_option
  alias: Default  Living Room Light to bright
  condition:
  - condition: state
    entity_id: input_select.light_state
    state: 'Off'
  id: '1524078506695'
  trigger:
  - entity_id: light.livingroom_light
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.wall_switch_left_158d0001a21f31
    service: switch.toggle
  alias: Link Hall Wireless Switch ( Hall)
  condition: []
  id: '1524219819384'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.wall_switch_right_158d00017110b8
    event_type: click
    platform: event
- action:
  - data:
      entity_id: switch.wall_switch_right_158d0001a21f31
    service: switch.toggle
  alias: Link Hall Wireless Switch ( Landing)
  condition: []
  id: '1524219997285'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.wall_switch_left_158d00017110b8
    event_type: click
    platform: event
- action:
  - data:
      entity_id: switch.wall_switch_158d0001a2424b
    service: switch.toggle
  alias: Link Maddy Wireless Button
  condition: []
  id: '1524220170929'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d00018721c6
    event_type: click
    platform: event
- action:
  - data:
      entity_id: switch.wall_switch_158d0001614701
    service: switch.turn_on
  - delay: 00:01:00
  - data:
      entity_id: switch.wall_switch_158d0001614701
    service: switch.turn_off
  alias: Motion Detect Porch LIght On
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  id: '1524228606038'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e43e18
    from: 'off'
    platform: state
    to: 'on'
- action:
  - delay: 00:05:00
  - data:
      entity_id: switch.wall_switch_158d00016cefdb
    service: switch.turn_off
  alias: Hall Toilet off after 5mins
  condition: []
  id: '1524229698425'
  trigger:
  - entity_id: switch.wall_switch_158d00016cefdb
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.wall_switch_158d000159aa50
    service: switch.toggle
  alias: Link Bedroom Wireless Switch
  condition: []
  id: '1524295022924'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.wall_switch_158d0001830c7c
    event_type: click
    platform: event
- action:
  - data:
      entity_id: switch.wall_switch_left_158d0001a6596b
    service: switch.turn_off
  alias: Turn off En-suite Light if bedroom light off
  condition: []
  id: '1524295829059'
  trigger:
  - entity_id: switch.wall_switch_158d000159aa50
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: group.gdownstairs
    service: homeassistant.turn_off
  - data:
      entity_id: switch.wall_switch_right_158d0001a21f31
    service: switch.turn_on
  alias: Turn Downstairs off double click Hall wireless switch
  condition: []
  id: '1524300935711'
  trigger:
  - event_data:
      click_type: both
      entity_id: binary_sensor.wall_switch_both_158d00017110b8
    event_type: click
    platform: event
- action:
  - data:
      entity_id: switch.wall_switch_left_158d0001a21f31
    service: switch.turn_on
  alias: 'Coming in '
  condition:
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0001e43e18
    state: 'on'
  - after: sunset
    before: sunrise
    condition: sun
  id: '1524316773814'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00019e1738
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: input_boolean.cube_state
    service: input_boolean.turn_on
  - data:
      gw_mac: 34CE0081452D
      ringtone_id: 11
      ringtone_vol: 8
    service: xiaomi_aqara.play_ringtone
  alias: Cube Activate
  condition:
  - condition: state
    entity_id: input_boolean.cube_state
    state: 'off'
  id: '1524562226338'
  trigger:
  - event_data:
      action_type: tap_twice
      entity_id: binary_sensor.cube_158d000103a8a5
    event_type: cube_action
    platform: event
- action:
  - delay: 00:10:00
  - data:
      entity_id: input_boolean.cube_state
    service: input_boolean.turn_off
  alias: Cube Time Set
  condition: []
  id: '1524563321892'
  trigger:
  - entity_id: input_boolean.cube_state
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: input_select.light_state
    service: input_select.select_next
  alias: Cube Flip 90 next light state LR
  condition:
  - condition: state
    entity_id: input_boolean.cube_state
    state: 'on'
  id: '1524564157806'
  trigger:
  - event_data:
      action_type: flip90
      entity_id: binary_sensor.cube_158d000103a8a5
    event_type: cube_action
    platform: event
- action:
  - data:
      entity_id: light.livingroom_light
    service: light.turn_off
  alias: Cube Shake Air turn off LR light
  condition:
  - condition: state
    entity_id: input_boolean.cube_state
    state: 'on'
  id: '1524564982371'
  trigger:
  - event_data:
      action_type: shake_air
      entity_id: binary_sensor.cube_158d000103a8a5
    event_type: cube_action
    platform: event
