homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.852063
  longitude: -2.20192
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 38
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/python_scripts

weather:
  - platform: openweathermap
    api_key: !secret owm_api
    mode: freedaily
    

# Enables the frontend

frontend:
  themes: !include_dir_merge_named themes
system_health:

mobile_app:

# Database 
recorder:
# Enables configuration UI
config:
http:
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running 
  # in Docker container, etc.
  cors_allowed_origins:
    - https://lonebaggie.duckdns.org:7080
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
# Discover some devices automatically
#discovery:
#  ignore:
#  - google_cast
# Allows you to issue voice commands from the frontend in enabled browsers
hassio:
conversation:

# Enables support for tracking state changes over time
logger:
  default: warn
  logs:
    homeassistant.components.automation: debug
    homeassistant.components.scripts: debug
# lovelace 
lovelace:
  mode: yaml
  


history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


# Text to speech
# tts:
#  - platform: google

# include yaml scripts
cover: !include cover.yaml
cloud: !include cloud.yaml     
automation old: !include_dir_list automation/
automation: !include automations.yaml

script: !include scripts.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
scene: !include scenes.yaml
light: !include light.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
media_player: !include mediaplayer.yaml
switch: !include switch.yaml
notify: !include notify.yaml
device_tracker: !include device_tracker.yaml
shell_command: !include shell_command.yaml
#timer: !include timer.yaml
asuswrt: 
  host: 192.168.1.1
  username: !secret asuswrt_user
  password: !secret asuswrt_password
tradfri:
  host: 192.168.1.88
  allow_tradfri_groups: true
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 7C49EB88B73C
      key: !secret xiaomi_key1

