homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.852063
  longitude: -2.20192
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 38
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/python_scripts

# Enables the frontend

frontend:
  themes: !include_dir_merge_named themes
system_health:

mobile_app:

# Database 
recorder:
discovery:  
# Enables configuration UI
config:
browser_mod:
http:
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running 
  # in Docker container, etc.
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
# Discover some devices automatically
#discovery:
#  ignore:
#  - google_cast
# Allows you to issue voice commands from the frontend in enabled browsers
hassio:
conversation:

# Enables support for tracking state changes over time
logger:
  default: warn
  logs:
    homeassistant.components.automation: debug
    homeassistant.components.scripts: debug
    homeassistant.components.xiaomi_gateway3: debug
# lovelace 
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-canary/canary.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-gap-card/gap-card.js
      type: module
    - url: /hacsfiles/lovelace-gui-sandbox/gui-sandbox.js
      type: module
    - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/flex-table-card/flex-table-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js
      type: module
    - url: /hacsfiles/channel-pad/card-channel-pad.js
      type: module


history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


# Text to speech
# tts:
#  - platform: google

# include yaml scripts
cover: !include cover.yaml
cloud: !include cloud.yaml 
automation old: !include_dir_list automation/
automation: !include automations.yaml
group: !include group.yaml
script: !include_dir_merge_named script
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
scene: !include scenes.yaml
light: !include light.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
media_player: !include mediaplayer.yaml
switch: !include switch.yaml
notify: !include notify.yaml
shell_command: !include shell_command.yaml
timer: !include timer.yaml
xiaomi_gateway3:
  debug: true
wake_on_lan: # enables `wake_on_lan` domain
webostv:
  host: 192.168.1.38
  #other settings
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 64:95:6C:FD:0D:5F
      broadcast_address: 192.168.1.255
  customize:
    sources:
      - AV
      - Amazon Music
      - Amazon Prime Video
      - BBC Sounds
      - BBC iPlayer
      - Blu-ray Player
      - Disney+
      - HDMI 1
      - HDMI 2
      - HDMI 3
      - Live TV
      - NOW TV
      - Netflix
      - Web Browser
      - YouTube