resources:
  - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/lovelace-canary/canary.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-gap-card/gap-card.js
    type: module
  - url: /hacsfiles/lovelace-gui-sandbox/gui-sandbox.js
    type: module
  - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/flex-table-card/flex-table-card.js
    type: module
  
background: var(--background-image)
excluded_entities:
  - weblink.router
preload:
  - markdown
  - gauge
  - conditional
  - entities
title: Home
views:
  - !include '/config/lovelace/alert.yaml'
  - !include '/config/lovelace/home.yaml'
  - !include '/config/lovelace/alexa.yaml'
  - !include '/config/lovelace/octopus.yaml'
  - !include '/config/lovelace/car.yaml'
  - !include '/config/lovelace/weather.yaml'
  - !include '/config/lovelace/rocket.yaml'
  - !include '/config/lovelace/zigbee.yaml'
  - !include '/config/lovelace/all.yaml'  
  - !include '/config/lovelace/sandbox.yaml'
  - !include '/config/lovelace/battery.yaml'
  - !include '/config/lovelace/input.yaml'
  - !include '/config/lovelace/switches.yaml'
  - !include '/config/lovelace/lights.yaml'
  - !include '/config/lovelace/media.yaml'
  - !include '/config/lovelace/sensors.yaml'
  - !include '/config/lovelace/bsensors.yaml'
  - !include '/config/lovelace/livingroom.yaml'
  - !include '/config/lovelace/kitchen.yaml'
  - !include '/config/lovelace/utility.yaml'
  - !include '/config/lovelace/hall.yaml'
  - !include '/config/lovelace/frontroom.yaml'
  - !include '/config/lovelace/outside.yaml'
  - !include '/config/lovelace/landing.yaml'
  - !include '/config/lovelace/study.yaml'
  - !include '/config/lovelace/masterbedroom.yaml'
  - !include '/config/lovelace/bathroom.yaml'
  - !include '/config/lovelace/francis.yaml'
  - !include '/config/lovelace/maddy.yaml'
  - !include '/config/lovelace/currentlocation.yaml'
  - !include '/config/lovelace/timers.yaml'
  
