
  
background: var(--background-image)
excluded_entities:
  - weblink.router
preload:
  - markdown
  - gauge
  - conditional
  - entities
title: Home
layout:
      width: 300
views:
  - !include '/config/lovelace/alert.yaml'
  - !include '/config/lovelace/home.yaml'
  - !include '/config/lovelace/TV.yaml'
  - !include '/config/lovelace/alexa.yaml'
  - !include '/config/lovelace/weather.yaml'
  - !include '/config/lovelace/car.yaml'
  - !include '/config/lovelace/rocket.yaml'
  - !include '/config/lovelace/all.yaml'  
  - !include '/config/lovelace/sandbox.yaml'
  - !include '/config/lovelace/battery.yaml'
  - !include '/config/lovelace/input.yaml'
  - !include '/config/lovelace/switches.yaml'
  - !include '/config/lovelace/lights.yaml'
  - !include '/config/lovelace/media.yaml'
  - !include '/config/lovelace/sensors.yaml'
  - !include '/config/lovelace/bsensors.yaml'
  - !include '/config/lovelace/livingroom.yaml'
  - !include '/config/lovelace/kitchen.yaml'
  - !include '/config/lovelace/utility.yaml'
  - !include '/config/lovelace/hall.yaml'
  - !include '/config/lovelace/frontroom.yaml'
  - !include '/config/lovelace/outside.yaml'
  - !include '/config/lovelace/landing.yaml'
  - !include '/config/lovelace/study.yaml'
  - !include '/config/lovelace/masterbedroom.yaml'
  - !include '/config/lovelace/bathroom.yaml'
  - !include '/config/lovelace/francis.yaml'
  - !include '/config/lovelace/maddy.yaml'
  - !include '/config/lovelace/currentlocation.yaml'
  - !include '/config/lovelace/timers.yaml'
  
