title: Home
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # House Overall View
  - id: 0  # Automatically created id
    icon: mdi:home-assistant
    title: Overview

    theme: dark-mode
    # The cards to show on this view.
    cards:
# who is home
      - id: f9f9d1e91dd6477eb621c9bfd8f1b257  # Automatically created id
        type: vertical-stack
        cards:
          - type: entity-filter
            entities:
              - entity: device_tracker.f6d013042725
                name: Simon
              - entity: device_tracker.android6c7f7b0a01e8c5c2
                name: Francis
              - entity: device_tracker.androidd237b1685b303ccd
                name: Louise
              - entity: device_tracker.androidaa6a31c8b0e2e4b6
                name: Madeline
            state_filter:
              - home
            show_empty: false
            card:
              type: glance
              title: Home
              show_state: false
          - type: entity-filter
            entities:
              - entity: device_tracker.f6d013042725
                name: Simon
              - entity: device_tracker.android6c7f7b0a01e8c5c2
                name: Francis
              - entity: device_tracker.androidd237b1685b303ccd
                name: Louise
              - entity: device_tracker.androidaa6a31c8b0e2e4b6
                name: Madeline
            state_filter:
              - not_home
            show_empty: false
            card:
              type: glance
              title: Away
              show_state: false
# House lights
      - id: 6aed2d9046b54164ad981bd4f3b710cf  # Automatically created id
        type: entity-filter
        entities:
          - switch.wall_switch_158d00016cf4bc
          - switch.wall_switch_158d0001614701
          - light.gateway_light_34ce0081452d
          - switch.wall_switch_158d000159a94f
          - switch.wall_switch_158d0001a68d54
          - switch.wall_switch_left_158d0001a21f31
          - switch.wall_switch_158d00016cefdb
          - switch.wall_switch_158d0001828c33
          - switch.wall_switch_158d0001a2424b
          - switch.wall_switch_158d00016cf458
          - switch.wall_switch_158d0001a68cf6
          - switch.wall_switch_158d000159aa50
          - switch.wall_switch_left_158d0001a6596b
          - switch.wall_switch_left_158d0001660d34
          - switch.wall_switch_right_158d0001a21f31
        state_filter:
          - on
        card:
          type: entities
          title: Lights left on
        show_empty: false

# temperature inside /outside
      - id: d9e4d3ec9cad4a048361879a38769b14  # Automatically created id
        type: glance
        title: Temperature
        entities:
          - entity: sensor.temperature_158d0001b9205b
            name: Inside
          - entity: sensor.dark_sky_temperature
            name: Outside
# darksky  weather
      - id: e58f68466bb34824bfb38d57506ae3e9  # Automatically created id
        type: weather-forecast
        entity: weather.dark_sky
#All lights / light switches
  - id: 1  # Automatically created id
    icon: mdi:lightbulb
    title: All lights
    cards:
      - id: cbdf81217f7848d1b0052b49296df9d0  # Automatically created id
        type: entities
        title: Downstairs
        entities:
          - switch.wall_switch_158d00016cf4bc
          - light.living_room_lights
          - light.dining_room_lights
          - switch.wall_switch_158d0001614701
          - light.gateway_light_34ce0081452d
          - switch.wall_switch_158d000159a94f
          - switch.wall_switch_158d0001a68d54
          - switch.wall_switch_left_158d0001a21f31
          - switch.wall_switch_158d00016cefdb
          - switch.wall_switch_158d0001828c33
      - id: 80878e4bac0b44c68da71ef0ea637dc3  # Automatically created id
        type: entities
        title: Upstairs
        entities:
          - switch.wall_switch_158d0001a2424b
          - switch.wall_switch_158d00016cf458
          - switch.wall_switch_158d0001a68cf6
          - switch.wall_switch_158d000159aa50
          - switch.wall_switch_left_158d0001a6596b
          - switch.wall_switch_left_158d0001660d34
          - switch.wall_switch_right_158d0001a21f31
# Alexa Devices
  - id: 2  # Automatically created id
    icon: mdi:amazon-alexa
    title: Alexa Devices
    cards:
      - id: 4f0aca6d8c064ee78d2a68ed35ee3ff6  # Automatically created id
        type: entities
        title: Alexa Devices
        show_header_toggle: false
        entities:
          - entity: media_player.lr_dot
            name: Livingroom Dot
            secondary_info: entity-id
            icon: mdi:amazon-alexa
          - entity: media_player.k_dot
            secondary_info: entity-id
            name: Kitchen Dot
            icon: mdi:amazon-alexa
          - entity: media_player.fr_dot
            name: Frontroom Dot
            secondary_info: entity-id
            icon: mdi:amazon-alexa
          - entity: media_player.br_echo
            name: Bedroom Echo
            secondary_info: entity-id
            icon: mdi:amazon-alexa
          - entity: input_boolean.audit_light
            name: Livingroom Audit
      - id: 047dc53ab4fc4d2e9ab7e62c689fc8dc  # Automatically created id
        type: entities
        title: TTS
        show_header_toggle: false
        entities:
          - entity: input_select.alexa_state
            name: Select Echo
      - id: aea1a6335ced498a9a7898aa14ba5a42  # Automatically created id
        type: conditional
        conditions:
          - entity: input_select.alexa_state
            state_not: None
        card:
          type: entities
          entities:
            - input_number.alexa_volume
            - type: divider
            - entity: input_text.tts
              name: Enter Text
      - id: 03e32403a7824bf098cb59962b432a98  # Automatically created id
        type: conditional
        conditions:
          - entity: media_player.sony_htxt2
            state: on
        card:
          type: media-control
          entity: media_player.sony_htxt2
# All sensors
  - id: 3  # Automatically created id
    icon: mdi:wrench
    title: Room sensors
    cards:
      - id: 0c8736ef4f3f405bb0471f5ecf3e09c4  # Automatically created id
        type: entities
        title: Sensors
        show_header_toggle: false
        entities:
          - binary_sensor.motion_sensor_158d0001655f53
          - binary_sensor.motion_sensor_158d000187392e
          - binary_sensor.motion_sensor_158d0001e43e18
          - binary_sensor.water_leak_sensor_158d0001c3472b
          - binary_sensor.water_leak_sensor_158d0001c347c9
          - binary_sensor.cube_158d000103a8a5_2
          - sensor.illumination_34ce0081452d
          - sensor.humidity_158d0001b9205b
          - sensor.pressure_158d0001b9205b
          - sensor.temperature_158d0001b9205b
# Raspberry Pi subsystems
  - id: 4  # Automatically created id
    icon: mdi:desktop-classic
    title: Raspberry Pi System
    cards:
      - id: 1220fa0439234bc19781777b1e043558  # Automatically created id
        type: entities
        title: Raspberry Pi subsystems
        show_header_toggle: false
        entities:
          - sensor.processor_use
          - sensor.memory_free
          - sensor.memory_use
          - sensor.disk_use_percent_
          - sensor.since_last_boot_templated
          - sensor.last_boot
# battery levels
  - id: 5  # Automatically created id
    icon: mdi:battery
    title: Battery Levels
    cards:
      - id: 5c2b0418500746b4adaf1fb1148624a8  # Automatically created id
        type: entities
        title: Battery levels
        show_header_toggle: false
        entities:
          - sensor.livingroom_wireless_switch_battery
          - sensor.hall_wireless_switch_battery
          - sensor.tradfri_dimmer_battery
          - sensor.button_switch_battery
          - sensor.cube_battery
          - sensor.frontdoor_battery
          - sensor.landing_motion_battery
          - sensor.hall_motion_battery
          - sensor.toilet_leak_sensor_battery
          - sensor.outside_motion_sensor_battery
          - sensor.patio_door_sensor_battery
          - sensor.temperaure__sensor_battery
          - sensor.utility_leak_sensor_battery
# Livingroom
  - id: 6  # Automatically created id
    icon: mdi:sofa
    title: Livingroom
    cards:
      - id: 1d977559df7142c49ed48c152d39d6ed  # Automatically created id
        type: vertical-stack
        cards:
          - type: entities
            title: Light Mode
            show_header_toggle: false
            entities:
              - switch.wall_switch_158d00016cf4bc
              - light.gateway_light_34ce0081452d
              - input_select.light_state
          - type: conditional
            conditions:
              - entity: switch.wall_switch_158d00016cf4bc
                state: on
            card:
              type: entities
              title: Living Room Lights
              show_header_toggle: true
              entities:
                - light.lr1_2
                - light.lr2
                - light.lr3_2
          - type: conditional
            conditions:
              - entity: switch.wall_switch_158d00016cf4bc
                state: on
            card:
              type: entities
              title: Dining Room Lights
              show_header_toggle: true
              entities:
                - light.dr1
                - light.dr2
                - light.dr3
      - id: 78503ddaf08742568e3581bc1bf98ffd  # Automatically created id
        type: vertical-stack
        cards:
          - type: entities
            title: Media
            entities:
              - sensor.harmony
          - type: conditional
            conditions:
              - entity: sensor.harmony
                state: Gigablue
            card:
              type: entities
              show_header_toggle: false
              entities:
                - sensor.tv_channel
                - sensor.tv_program
                - media_player.sony_htxt2
          - type: conditional
            conditions:
              - entity: sensor.harmony
                state: Roku
            card:
              type: entities
              title: Ruko
              show_header_toggle: false
              entities:
                - media_player.living_room
                - media_player.sony_htxt2
          - type: conditional
            conditions:
              - entity: sensor.harmony
                state: Sony
            card:
              type: entities
              title: Sony
              show_header_toggle: false
              entities:
                - media_player.sony_htxt2
          - type: conditional
            conditions:
              - entity: sensor.harmony
                state: Speaker
            card:
              type: entities
              title: BT Speaker
              show_header_toggle: false
              entities:
                - media_player.lr_dot
                - media_player.sony_htxt2
          - type: conditional
            conditions:
              - entity: sensor.harmony
                state: LG
            card:
              type: entities
              title: LG TV
              show_header_toggle: false
              entities:
                - media_player.lg_tv_remote
                - media_player.sony_htxt2
          - type: conditional
            conditions:
              - entity: input_select.harmony_state
                state: Blue Ray
            card:
              type: entities
              title: LG BR Player
              show_header_toggle: false
              entities:
                - media_player.sony_htxt2
      - id: ec8f6dec3a9b482bbaedc6e5b9c25eb8  # Automatically created id
        type: entities
        title: Switches
        show_header_toggle: false
        entities:
          - binary_sensor.door_window_sensor_158d00019e18bf
          - switch.onoff_sonoff1
          - switch.onoff_sonoff2
          - switch.onoff_sonoffbasic1
# kitchen
  - id: 7  # Automatically created id
    icon: mdi:food-variant
    title: Kitchen
    cards:
      - id: f56aebf41cde412caf5660d539b03ee1  # Automatically created id
        type: entities
        show_header_toggle: false
        title: Kitchen
        entities:
          - switch.wall_switch_158d000159a94f
          - entity: media_player.k_dot
            icon: mdi:amazon-alexa
# Utility
  - id: 8  # Automatically created id
    icon: mdi:washing-machine
    title: Utility
    cards:
      - id: 143fac23d10042b8b59f52a381de5eb7  # Automatically created id
        type: entities
        title: Utility
        show_header_toggle: false
        entities:
          - switch.wall_switch_158d0001a68d54
          - binary_sensor.water_leak_sensor_158d0001c347c9
# Hall
  - id: 9  # Automatically created id
    icon: mdi:clock
    title: Hall
    cards:
      - id: 906d0aa0ac404f37805e06e372fa3bd0  # Automatically created id
        type: entities
        title: Hall
        show_header_toggle: false
        entities:
          - switch.wall_switch_left_158d0001a21f31
          - binary_sensor.door_window_sensor_158d00019e1738
          - input_boolean.ms2
          - binary_sensor.motion_sensor_158d0001655f53
          - switch.wall_switch_158d00016cefdb
          - binary_sensor.water_leak_sensor_158d0001c3472b
# Frontroom
  - id: 10  # Automatically created id
    icon: mdi:sofa
    title: Frontroom
    cards:
      - id: 7f7ea1e9970d4093af6b3d7ca2cfc523  # Automatically created id
        type: entities
        title: Frontroom
        show_header_toggle: false
        entities:
          - input_boolean.ms1
          - binary_sensor.motion_sensor_158d000187392e
          - switch.wall_switch_158d0001828c33
          - entity: media_player.fr_dot
            icon: mdi:amazon-alexa
#Outside
  - id: 11  # Automatically created id
    icon: mdi:flower
    title: Outside
    cards:
      - id: 486a4f2d2ab74b4aa11d43e769c339e9  # Automatically created id
        type: entities
        title: Outside
        show_header_toggle: false
        entities:
          - switch.wall_switch_158d0001614701
          - sensor.illumination_158d0001e43e18
          - binary_sensor.motion_sensor_158d0001e43e18
          - input_boolean.ms3
# Landing
  - id: 12  # Automatically created id
    icon: mdi:glassdoor
    title: Landing
    cards:
      - id: 0871354a1b89414da9f5b2c1a82e0360  # Automatically created id
        type: entities
        title: Landing
        show_header_toggle: false
        entities:
          - switch.wall_switch_right_158d0001a21f31
# Main Baathroom
  - id: 13  # Automatically created id
    icon: mdi:human-male-female
    title: Main Bathroom
    cards:
      - id: a01593ee38b44df496ccf9700487bac2  # Automatically created id
        type: entities
        title: Main Bathroom
        show_header_toggle: false
        entities:
          - switch.wall_switch_left_158d0001660d34
          - switch.wall_switch_right_158d0001660d34
# Master Bathroom
  - id: 14  # Automatically created id
    icon: mdi:hotel
    title: Master Bedroom
    cards:
      - id: cbfd9769ad104eb7af839bc8ba463a57  # Automatically created id
        type: entities
        title: Master Bedroom
        show_header_toggle: false
        entities:
          - switch.wall_switch_158d000159aa50
          - switch.wall_switch_left_158d0001a6596b
          - switch.wall_switch_right_158d0001a6596b
          - entity: media_player.br_echo
            icon: mdi:amazon-alexa
# Study
  - id: 15  # Automatically created id
    icon: mdi:book-open-variant
    title: Study
    cards:
      - id: bcc8f42fc61c4e1b8e84cd5537a4d1a8  # Automatically created id
        type: entities
        title: Study
        show_header_toggle: false
        entities:
          - switch.wall_switch_158d0001a68cf6
# Francis Room
  - id: 16  # Automatically created id
    icon: mdi:hotel
    title: Francis's Room
    cards:
      - id: 5037e09eb47543a7af78d5cb25f18b49  # Automatically created id
        type: entities
        title: Francis's Room
        show_header_toggle: false
        entities:
          - switch.wall_switch_158d00016cf458
# Maddy room
  - id: 17  # Automatically created id
    icon: mdi:hotel
    title: Maddy Room
    cards:
      - id: 6e4ca575ee684cce80146e2ee9427cea  # Automatically created id
        type: entities
        title: Maddy Room
        show_header_toggle: false
        entities:
          - switch.wall_switch_158d0001a2424b
          - binary_sensor.switch_158d00018721c6






