alias: Check state of Gigablue Sat Box
description: Ensure Gigablue is synced on or off correctly
trigger:
  entity_id: sensor.harmony
  platform: state
action:
  
  - service_template: >
      {% if states.sensor.harmony.state == "TV" %}
        media_player.turn_on
      {% else %}
        media_player.turn_off
      {% endif %}
    data:
      entity_id: media_player.enigma_2
  