alias: Check Light Mood
description: keep item select in sync 

trigger:
    platform: state
    entity_id: sensor.light_state
    
condition:
  condition: template
  value_template: >
    (% if states.sensor.light_state.state == 'Off' 
       or states.sensor.light_state.state == states.sensor.light_state.state
    %)
        false
    (% else %)
        true
    ( % endif %)
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.light_state
      option: > 
        {% if states("switch.0x158d00016cf4bc_switch") == 'off' %}
          Off
        {% else %}
          {{states.sensor.light_state.state}}
        {% endif %}