alias: Check Light Mood
description: keep item select in sync 
trigger:
    platform: time_pattern
    minutes: "/3"
condition:
    condition: state
    entity_id: light.living_room
    state: 'on'
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.light_state
      option: '{{states.sensor.light_state.state}}'