alias: Dummy light to item select
description: Trigger item select from dummy light
trigger:
  entity_id: light.alexa_virtual
  platform: state
condition: 
  - condition: state
    entity_id: light.alexa_virtual
    state: 'on'
action:
  - service: input_select.select_option
    data_template:  
      entity_id: input_select.speak_list
      option: >
        {% set slist = state_attr("input_select.speak_list","options") %}
        {% set opt = state_attr('light.alexa_virtual','brightness') %}
        {% if opt|int > slist|length %}
          {% set opt= 0 %}
        {% endif %}
        {{slist[opt]}}
  - service: light.turn_off
    data:
      entity_id: light.alexa_virtual
