alias: Ensure Sony Turns is on  when Harmony on
description: Harmony remote gets out of sync
trigger:
  entity_id: media_player.sony_htxt2
  platform: state
  to: 'off'

action:
  - delay: 00:00:10
  - condition: state
    entity_id: remote.harmony_hub
    state: 'on'
  - condition: state
    entity_id: media_player.sony_htxt2
    state: 'off'
  - service: media_player.turn_on
    data:
      entity_id: media_player.sony_htxt2
