alias: Force tradfri to unavailable
description: tradfri lights take a long time to become unavailiable  when power removed. 
trigger:
  entity_id: switch.wall_switch_158d00016cf4bc
  platform: state
  from : 'on'
  to: 'off'
  for:
    seconds: '60'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.light_state
      option: 'Off'
  - delay: '00:00:05'
  - service: light.turn_off
    data:
      entity_id: light.dining_room
  - service: light.turn_off
    data:
      entity_id: light.sitting_room
  - service: light.turn_on
    data:
      entity_id: light.dining_room
  - service: light.turn_on
    data:
      entity_id: light.sitting_room
  - service: light.turn_off
    data:
      entity_id: light.sitting_room
  - service: light.turn_off
    data:
      entity_id: light.dining_room
    
  
    