alias: Input Select to lights 
description: control lights from item select
trigger:
  entity_id: input_select.light_state
  platform: state
condition:
  - condition: template
    value_template: >
      {% if states.input_select.light_state.state == "Unknown" %}
        false
      {% else %}
        true
      {% endif %}
action:
  - service_template: >
      {% if states.input_select.light_state.state == "Off" %}
        light.turn_off
      {% else %}
        light.turn_on
      {% endif %}
    data:
      entity_id: light.living_room
  - condition: template
    value_template: >
      {% if states.input_select.light_state.state == "Off" %}
        false
      {% else %}
        true
      {% endif %}
  - delay: 
      seconds: >
        {% if trigger.from_state.state == "Off" %}
          40
        {% else %}
            0
        {% endif %}
  - service:
      switch.turn_on
    data_template:
      entity_id: >
        switch.{{states.input_select.light_state.state}}
    