alias: Input Select to lights 
description: control lights from item select
trigger:
  entity_id: input_select.light_state
  platform: state
condition:
  - condition: template
    value_template: >
      {% if states.input_select.light_state.state == "Unknown" %}
        false
      {% else %}
        true
      {% endif %}
action:
  - service_template: >
      {% if states.input_select.light_state.state == "Off" %}
        switch.turn_off
      {% else %}
        switch.turn_on
      {% endif %}
    data:
      entity_id: switch.living_room
  - condition: template
    value_template: >
      {% if states.input_select.light_state.state == "Off" %}
        false
      {% else %}
        true
      {% endif %}
  - delay: 
      seconds: >
        {% if trigger.from_state.state == "Off" %}
          40
        {% else %}
            0
        {% endif %}
  - service: light.turn_on
    data_template:
      entity_id: light.living_room
      transition: 3
      brightness: >
        {% if states.input_select.light_state.state == "Dark" %}
          1
        {% elif states.input_select.light_state.state == "Relaxed" %}
          170
        {% elif states.input_select.light_state.state == "Bright" %}
          254
        {% endif %}
  - delay: 00:00:04
  - service: light.turn_on
    data_template:
      entity_id: light.living_room
      transition: 3
      color_temp: >
        {% if states.input_select.light_state.state == "Dark" %}
          454
        {% elif states.input_select.light_state.state == "Relaxed" %}
          400
        {% elif states.input_select.light_state.state == "Bright" %}
          200
        {% endif %}