alias: Input Select to Radio
description: Turn on BBC radio via Input Select 
trigger:
  platform: state
  entity_id: input_select.radio_state

action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.harmony_state
      option: >
        {% if is_state('input_select.radio_state','Off') %}
          PowerOff   
        {% else %}
          Radio
        {% endif %} 
        
  - service_template: >
      {% if is_state('input_select.harmony_state','Radio') %}
        media_player.turn_on
      {% else %}
        media_player.turn_off
      {% endif %}
    data:
      entity_id: media_player.enigma_2
  - condition: template
    value_template: "{{is_state('input_select.harmony_state', 'Radio')}}"
  - service_template: > 
      {% if is_state('switch.tv_radio_1', 'on') %}
        shell_command.radio1
      {% elif is_state('switch.tv_radio_2', 'on') %}
        shell_command.radio2
      {% elif is_state('switch.tv_radio_3', 'on') %}
        shell_command.radio3
      {% elif is_state('switch.tv_radio_4', 'on') %}
        shell_command.radio4
      {% endif %}
      
      
  