alias: Item Select to speak
description: Trigger Alexa from Item Select
trigger:
  entity_id: input_select.speak_list
  platform: state
condition:
  - condition: template
    value_template: '{{states.input_select.speak_list.state != "do not use"  }}'
action:
  - service_template: >
        {% set name = states('sensor.last_alexa').split('.') %}
        notify.alexa_media_{{name[-1]}}
    data_template:
      data:
        type: tts
      message: >
        {% set elist = state_attr("input_select.entity_list","options") %}
        {% set slist = states.input_select.speak_list.state %}
        {% set slist = slist.split() %}
        {% set ns=namespace(state = "") %}
        {% for obj in slist %}
          {% if obj == "(tt)" %}
            {% set obj = now().strftime("%-I %M %p") %}
            {% set mn = now().strftime("%M") %}
            {% if mn|int < 10 %}
              {% set obj = obj[:2] ~ obj[2:]|replace('0','oh ') %}
            {% endif %}
          {% endif %}
          {% if obj == "(td)" %}
            {% set obj = now().strftime("%A, %d. %B %Y") %}
          {% endif %}
          {% if obj == "(gr)" %}
            {% if now().hour < 12 %}
              {% set obj = "Good Morning" %}
            {% elif now().hour < 17 %}
              {% set obj = "Good Afternoon" %}
            {% else %}
              {% set obj = "Good Evening" %}
            {% endif %}
          {% endif %}
          {% if obj[:2] == "(e" %}
            {% set enum = obj[2:4]|int %}
            {% set ent = elist[enum] %}
            {% set state = states(ent)|round(1) %}
            {% if state == None %}
              {% set state = "unknown" %}
            {% endif %}
            {% set uom = state_attr(ent,"unit_of_measurement") %}
            {% if uom == None %}
              {% set uom = "" %}
            {% endif %}
            {% set devtype = state_attr(ent,"device_class") %}
            {% if devtype == None %}
              {% set devtype = "" %}
            {% endif %}
            {% if obj[4:5]|regex_search('[0-9]') %}
              {% set alist =states[ent]['attributes']|list %}
              {% set num = obj[4:5]|int %}
              {% set obj = state_attr(ent,alist[num])|string  %}
              {% set devtype = "" %}
            {% elif obj[4:5] == "s" %}
              {% set obj = state ~ " " ~ uom %}
            {% elif obj[4:5] == "$" %}
              {% set obj = state  %}
            {% elif obj[4:5] == "f" %}
              {% set obj = state_attr(ent,"friendly_name")|regex_replace("[(/[\W_]+/g," ")]") %}
              {% set devtype = "" %}
            {% elif obj[4:5] in ["b","B"] %}
              {% set bri = state_attr(ent,"brightness") %}
              {% if bri == None %}
                {% set bri = 0 %}
              {% endif %}
              {% if obj[4:5] == "B" %}
                {% set obj = bri|string %}
              {% else %}
                {% set obj = ((100*bri/254)|int)|string %}
              {% endif %}
            {% endif %}
            {% if devtype in ["opening","window","door","garage_door"] %}
              {% set obj = obj|replace('off','closed') %}
              {% set obj = obj|replace('on','open') %}
            {% endif %}
            {% if devtype in ["lock"] %}
              {% set obj = obj|replace('off','unlocked') %}
              {% set obj = obj|replace('on','locked') %}
            {% endif %}
            {% if devtype in ["battery_charging"] %}
              {% set obj = obj|replace('off','not charging') %}
              {% set obj = obj|replace('on','charging') %}
            {% endif %}
            {% if devtype in  ["presence"] %}
              {% set obj = obj|replace('off','away') %}
              {% set obj = obj|replace('on','home') %}
            {% endif %}
            {% if devtype in ["connectivity"] %}
              {% set obj = obj|replace('off','not connected') %}
              {% set obj = obj|replace('on','connected') %}
            {% endif %}
            {% if devtype in ["vibration","smoke","sound","motion","occupancy",] %}
              {% set obj = obj|replace('off','clear') %}
              {% set obj = obj|replace('on','detected') %}
            {% endif %}
          {% endif %}
          {% set ns.state = ns.state + " " ~ obj  %}
        {% endfor %}
        {{ns.state}}
  - service: input_select.select_option
    data:
      entity_id: input_select.speak_list
      option: "do not use"