alias: Lights to input select
description: Turn off Item select if lights off
trigger:
  entity_id: light.living_room
  platform: state
  from: 'on'
  to: 'off'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.light_state
      option: 'Off'
  