alias: Sync Kitchen and Utility Light
description: Turn off utility light when Kitchen off
trigger:
  entity_id: switch.kitchen
  platform: state
  from: 'on'
  to: 'off'
condition:
  entity_id: switch.utility
  condition: state
  state: 'on'
action:
  service: switch.turn_off
  data:
    entity_id: switch.utility