
id: sync_kitchen_and_utility_light
alias: Sync Kitchen and Utility Light
description: Turn off utility light when Kitchen off
trigger:
  entity_id: light.kitchen
  platform: state
  from: 'on'
  to: 'off'
condition:
  entity_id: light.utility
  condition: state
  state: 'on'
action:
  service: light.turn_off
  data:
    entity_id: light.utility
