alias: TV default to Live TV
description: Force TV to switch to Live TV 
trigger:
  entity_id: media_player.lg_webos_smart_tv
  platform: state
  from: 'off'
  to: 'on'
action:

  - service: media_player.select_source 
    data:
      entity_id: media_player.lg_webos_smart_tv
      source: Live TV
 